const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
    basePath: '/',
  },
<<<<<<< HEAD
  apis: ['./model/user.js','./model/topic.js','./model/notice.js','./model/subscribe.js','./model/content.js','./model/article.js','./model/tag.js','./model/ward.js'],
=======
  apis: ['./model/user.js','./model/topic.js','./model/notice.js','./model/subscribe.js','./model/article.js','./model/comment.js','./model/content.js','./model/hashtag.js','./model/tag.js'],
>>>>>>> fc6771904bb142ec1c392ea35d2934c048b1bc83
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
  app.use('/api-docs',swaggerUi.serve, swaggerUi.setup(specs));
}
